#!/usr/bin/env python3
"""
Environment Setup Script for AgenticBot
This script helps you configure the required API keys
"""

import os
import sys

def create_env_file():
    """Create a .env file with the required API keys."""
    print("🔧 AgenticBot Environment Setup")
    print("=" * 50)
    print("This script will help you set up the required API keys.")
    print("You'll need:")
    print("1. 🔑 Google API Key (for Gemini AI)")
    print("2. 🕷️ Firecrawl API Key (for web scraping)")
    print("")
    
    # Get API keys from user
    print("📝 Please enter your API keys:")
    print("")
    
    google_key = input("🔑 Google API Key: ").strip()
    if not google_key:
        print("❌ Google API Key is required!")
        return False
    
    firecrawl_key = input("🕷️ Firecrawl API Key: ").strip()
    if not firecrawl_key:
        print("❌ Firecrawl API Key is required!")
        return False
    
    # Create .env file
    env_content = f"""# AgenticBot Environment Configuration
# Generated by setup_env.py

# Google Generative AI API Key
# Get from: https://makersuite.google.com/app/apikey
GOOGLE_API_KEY={google_key}

# Firecrawl API Key  
# Get from: https://www.firecrawl.dev/
FIRECRAWL_API_KEY={firecrawl_key}
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("")
        print("✅ Environment file created successfully!")
        print("📁 File location: .env")
        print("")
        print("🚀 You can now run AgenticBot:")
        print("   • CLI: python main.py")
        print("   • Web: streamlit run streamlit_app.py") 
        print("   • Test: python test_successful_prompts.py")
        print("")
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def check_existing_env():
    """Check if environment variables are already set."""
    google_key = os.getenv("GOOGLE_API_KEY")
    firecrawl_key = os.getenv("FIRECRAWL_API_KEY")
    
    if google_key and firecrawl_key:
        print("✅ API keys are already configured!")
        print(f"   Google API Key: {'*' * (len(google_key) - 4) + google_key[-4:]}")
        print(f"   Firecrawl API Key: {'*' * (len(firecrawl_key) - 4) + firecrawl_key[-4:]}")
        return True
    
    missing = []
    if not google_key:
        missing.append("GOOGLE_API_KEY")
    if not firecrawl_key:
        missing.append("FIRECRAWL_API_KEY")
    
    print("⚠️ Missing API keys:")
    for key in missing:
        print(f"   • {key}")
    
    return False

def load_env_file():
    """Load environment variables from .env file."""
    if not os.path.exists('.env'):
        return False
    
    try:
        with open('.env', 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()
        return True
    except Exception as e:
        print(f"❌ Error loading .env file: {e}")
        return False

def show_api_instructions():
    """Show instructions for getting API keys."""
    print("\n📖 How to get API keys:")
    print("")
    print("🔑 Google API Key:")
    print("   1. Go to https://makersuite.google.com/app/apikey")
    print("   2. Sign in with your Google account")
    print("   3. Click 'Create API Key'")
    print("   4. Copy the generated key")
    print("")
    print("🕷️ Firecrawl API Key:")
    print("   1. Go to https://www.firecrawl.dev/")
    print("   2. Sign up for an account")
    print("   3. Go to your dashboard")
    print("   4. Copy your API key")
    print("")

def main():
    """Main setup function."""
    print("🚀 AgenticBot Setup")
    print("=" * 30)
    
    # Try to load existing .env file
    if os.path.exists('.env'):
        print("📁 Found existing .env file, loading...")
        load_env_file()
    
    # Check current environment
    if check_existing_env():
        print("\n🎉 Your AgenticBot is ready to use!")
        return
    
    print("\n" + "="*50)
    choice = input("\nWould you like to:\n1. Set up API keys now\n2. See instructions for getting API keys\n3. Exit\n\nChoice (1-3): ").strip()
    
    if choice == "1":
        if create_env_file():
            print("\n🔄 Loading new environment...")
            load_env_file()
            check_existing_env()
    elif choice == "2":
        show_api_instructions()
        print("\n💡 After getting your keys, run this script again to set them up!")
    else:
        print("\n👋 Setup cancelled. Run this script again when you're ready!")

if __name__ == "__main__":
    main() 